<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
	  <AspNetCoreHostingModel>OutOfProcess</AspNetCoreHostingModel>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="Program.cs">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Compile>
  </ItemGroup>

	<ItemGroup>
		<Content Include="google548260b285c2a324.html" CopyToOutputDirectory="Always" CopyToPublishDirectory="Always" />
	</ItemGroup>

</Project>
